Name:           ros-melodic-simple-grasping
Version:        0.2.2
Release:        0%{?dist}
Summary:        ROS simple_grasping package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/simple_grasping
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-melodic-actionlib
Requires:       ros-melodic-geometry-msgs
Requires:       ros-melodic-grasping-msgs
Requires:       ros-melodic-message-runtime
Requires:       ros-melodic-moveit-msgs
Requires:       ros-melodic-moveit-python
Requires:       ros-melodic-pcl-ros
Requires:       ros-melodic-roscpp
Requires:       ros-melodic-sensor-msgs
Requires:       ros-melodic-shape-msgs
Requires:       ros-melodic-tf
BuildRequires:  ros-melodic-actionlib
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-cmake-modules
BuildRequires:  ros-melodic-geometry-msgs
BuildRequires:  ros-melodic-grasping-msgs
BuildRequires:  ros-melodic-message-generation
BuildRequires:  ros-melodic-moveit-msgs
BuildRequires:  ros-melodic-pcl-ros
BuildRequires:  ros-melodic-roscpp
BuildRequires:  ros-melodic-sensor-msgs
BuildRequires:  ros-melodic-shape-msgs
BuildRequires:  ros-melodic-tf

%description
Basic grasping applications and demos.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Mon Aug 13 2018 Michael Ferguson <mferguson@fetchrobotics.com> - 0.2.2-0
- Autogenerated by Bloom

